#!/usr/bin/env bash
set -euo pipefail

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}/.."

if [[ -x ".venv/bin/python" ]]; then
  export PATH="${PWD}/.venv/bin:${PATH}"
  export PYTHON_BIN="${PYTHON_BIN:-.venv/bin/python}"
fi

export REPORT_LABEL="${REPORT_LABEL:-harness_aware_combined_$(date +%Y%m%d_%H%M%S)}"
export HARNESSES="${HARNESSES:-hatcher}"
export PRESSURE_LEVELS="${PRESSURE_LEVELS:-p3_high}"

# Additive matrix:
# - no_prefetch: baseline
# - controller_harness_aware_sched: Scenario 1 ready-time scheduling only
# - controller_harness_aware_sched_kv: scheduling + Scenario 2 direct KV prepare
# - controller_harness_aware_sched_evict: scheduling + Scenario 3 value-aware eviction
# - controller_harness_aware_full: scheduling + direct KV prepare + value-aware eviction
export MODES="${MODES:-no_prefetch controller_harness_aware_sched controller_harness_aware_sched_kv controller_harness_aware_sched_evict controller_harness_aware_full}"

export P3_HIGH_KNOBS="${P3_HIGH_KNOBS:-tool_wait_ms=1000 target_prompt_tokens=4096 filler_sessions=15 filler_prompt_tokens=4096 session_count=1 concurrency=6}"
export TASK_REPLAY_STEPS="${TASK_REPLAY_STEPS:-2}"
export FILLER_REPLAY_DEADLINES="${FILLER_REPLAY_DEADLINES:-1}"
export TOOL_WAIT_PROFILE="${TOOL_WAIT_PROFILE:-realistic_deadline_fair}"
export TOOL_WAIT_PROFILE_SPEC="${TOOL_WAIT_PROFILE_SPEC:-very_short:20:100-500,short:35:1000-5000,medium:30:10000-30000,long:15:60000-120000}"
export TOOL_WAIT_SEED="${TOOL_WAIT_SEED:-20260922}"
export WORKLOAD_SHAPE_MODE_INDEPENDENT="${WORKLOAD_SHAPE_MODE_INDEPENDENT:-1}"
export AGENTIC_WORKLOAD_PROFILE="${AGENTIC_WORKLOAD_PROFILE:-synthetic_pressure}"

export MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-12288}"
export TRACE_PROFILE="${TRACE_PROFILE:-controller_decision}"
export TRACE_CONTROLLER_DECISIONS="${TRACE_CONTROLLER_DECISIONS:-1}"
export TRACE_CONTROLLER_COMPLETION_LINKAGE="${TRACE_CONTROLLER_COMPLETION_LINKAGE:-1}"
export TRACE_REPLAY_FRICTION_DEEP_DIVE="${TRACE_REPLAY_FRICTION_DEEP_DIVE:-1}"
export TRACE_REPLAY_BLOCKERS="${TRACE_REPLAY_BLOCKERS:-1}"
export AGENTIC_KV_TRACE_KV_POOL="${AGENTIC_KV_TRACE_KV_POOL:-1}"
export AGENTIC_KV_COPY_TELEMETRY_ENABLE="${AGENTIC_KV_COPY_TELEMETRY_ENABLE:-1}"
export AGENTIC_KV_GPU_UTIL_SAMPLER="${AGENTIC_KV_GPU_UTIL_SAMPLER:-1}"

export AGENTIC_KV_TARGETED_PREFETCH_HOOK="${AGENTIC_KV_TARGETED_PREFETCH_HOOK:-1}"
export AGENTIC_KV_PREPARE_CONTROL_ENABLE="${AGENTIC_KV_PREPARE_CONTROL_ENABLE:-1}"
export AGENTIC_KV_PREPARE_CONTROL_HOST="${AGENTIC_KV_PREPARE_CONTROL_HOST:-127.0.0.1}"
export AGENTIC_KV_PREPARE_CONTROL_PORT="${AGENTIC_KV_PREPARE_CONTROL_PORT:-31991}"
export AGENTIC_KV_PREPARE_CONTROL_URL="${AGENTIC_KV_PREPARE_CONTROL_URL:-http://127.0.0.1:31991/prepare_prefix_kv}"
export AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS="${AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS:-5000}"
export CONTROLLER_DIRECT_LOAD_MECHANISM="${CONTROLLER_DIRECT_LOAD_MECHANISM:-prepared_prefix_control}"
export CONTROLLER_DIRECT_LOAD_FIXED_MS="${CONTROLLER_DIRECT_LOAD_FIXED_MS:-1000}"
export CONTROLLER_DIRECT_LOAD_MS_PER_TOKEN="${CONTROLLER_DIRECT_LOAD_MS_PER_TOKEN:-2.0}"
export CONTROLLER_DIRECT_LOAD_ESTIMATE_MULTIPLIER="${CONTROLLER_DIRECT_LOAD_ESTIMATE_MULTIPLIER:-3.0}"
export CONTROLLER_DIRECT_LOAD_SAFETY_MARGIN_MS="${CONTROLLER_DIRECT_LOAD_SAFETY_MARGIN_MS:-750}"
export CONTROLLER_DIRECT_LOAD_REQUIRE_COMPLETION="${CONTROLLER_DIRECT_LOAD_REQUIRE_COMPLETION:-1}"
export CONTROLLER_DIRECT_LOAD_ALLOWED_WAIT_CLASSES="${CONTROLLER_DIRECT_LOAD_ALLOWED_WAIT_CLASSES:-long}"
export CONTROLLER_DIRECT_LOAD_SELECTIVE_ADMISSION="${CONTROLLER_DIRECT_LOAD_SELECTIVE_ADMISSION:-1}"
export CONTROLLER_DIRECT_LOAD_MIN_SAVED_TOKENS="${CONTROLLER_DIRECT_LOAD_MIN_SAVED_TOKENS:-1024}"

export CONTROLLER_VALUE_AWARE_RADIX_EVICTION_POLICY="${CONTROLLER_VALUE_AWARE_RADIX_EVICTION_POLICY:-priority}"
export CONTROLLER_EVICTION_LOW_REUSE_PROBABILITY="${CONTROLLER_EVICTION_LOW_REUSE_PROBABILITY:-0.15}"
export CONTROLLER_EVICTION_LOW_RECOMPUTE_TOKENS="${CONTROLLER_EVICTION_LOW_RECOMPUTE_TOKENS:-256}"

export CONTROLLER_REPLAY_ADMISSION_GUARD="${CONTROLLER_REPLAY_ADMISSION_GUARD:-1}"
export CONTROLLER_REPLAY_LOOKAHEAD_MS="${CONTROLLER_REPLAY_LOOKAHEAD_MS:-5000}"
export CONTROLLER_REPLAY_SAFETY_MARGIN_MS="${CONTROLLER_REPLAY_SAFETY_MARGIN_MS:-500}"
export CONTROLLER_MAX_HOLD_MS="${CONTROLLER_MAX_HOLD_MS:-10000}"
export CONTROLLER_ALLOW_SMALL_WORK_TOKENS="${CONTROLLER_ALLOW_SMALL_WORK_TOKENS:-256}"
export CONTROLLER_GPU_TELEMETRY_POLL_MS="${CONTROLLER_GPU_TELEMETRY_POLL_MS:-250}"
export CONTROLLER_GPU_IDLE_UTIL_THRESHOLD_PCT="${CONTROLLER_GPU_IDLE_UTIL_THRESHOLD_PCT:-5}"
export CONTROLLER_GPU_IDLE_RECENT_WINDOW_MS="${CONTROLLER_GPU_IDLE_RECENT_WINDOW_MS:-500}"
export CONTROLLER_GPU_BACKFILL_MAX_RUNTIME_MS="${CONTROLLER_GPU_BACKFILL_MAX_RUNTIME_MS:-1000}"

export REPORT_BUILDER_MODE="${REPORT_BUILDER_MODE:-rich}"
export UPDATE_LATEST="${UPDATE_LATEST:-1}"

echo "Harness-aware combined realistic run"
echo "REPORT_LABEL=${REPORT_LABEL}"
echo "MODES=${MODES}"
echo "P3_HIGH_KNOBS=${P3_HIGH_KNOBS}"
echo "TOOL_WAIT_PROFILE_SPEC=${TOOL_WAIT_PROFILE_SPEC}"
echo "TOOL_WAIT_SEED=${TOOL_WAIT_SEED}"
echo "DIRECT_KV_PREPARE=${CONTROLLER_DIRECT_LOAD_MECHANISM}"
echo "VALUE_AWARE_EVICTION_POLICY=${CONTROLLER_VALUE_AWARE_RADIX_EVICTION_POLICY}"
echo "ADDITIVE_MATRIX=baseline -> scheduling -> scheduling+kv -> scheduling+eviction -> full"

if [[ "${SKIP_PRIORITY_EVICTION_SMOKE:-0}" != "1" ]]; then
  report_dir="${REPORT_DIR:-artifacts/results/reports/${REPORT_LABEL}}"
  mkdir -p "${report_dir}"
  "${PYTHON_BIN:-python}" scripts/smoke_priority_radix_eviction.py \
    --out-json "${report_dir}/priority_radix_eviction_smoke.json"
fi

bash scripts/run_harness_deadline_pressure.sh "${MODEL}"

"${PYTHON_BIN:-python}" scripts/build_value_aware_eviction_audit.py \
  --run-root "${RUN_ROOT:-artifacts/results/runs/controlled/${REPORT_LABEL}}" \
  --report-dir "${REPORT_DIR:-artifacts/results/reports/${REPORT_LABEL}}"
