# Reproducible paired hardware probe; generated by infra/container/run_kv_movement_interference_reference.sh.
MODEL='Qwen/Qwen2.5-Coder-7B-Instruct'
BACKEND_RUNTIME_PROFILE='nvidia_standard'
SGLANG_DOCKER_IMAGE='agentic-sglang-standard:0.5.10.post1'
AGENTIC_MODEL_CACHE='${HOME}/.cache/huggingface'
REPORT_LABEL='hardware_kv_movement_large_final_20260928_224413'
SAMPLE_SET_ID='hardware_kv_movement_large_final_20260928_224413_samples'
TRIALS='4'
SEED='7'
DONOR_PROMPT_TOKENS='4090'
MINIMUM_HOST_TOKENS='512'
MIN_LOAD_TOKENS=''
export BACKEND_RUNTIME_PROFILE SGLANG_DOCKER_IMAGE AGENTIC_MODEL_CACHE REPORT_LABEL SAMPLE_SET_ID TRIALS SEED DONOR_PROMPT_TOKENS MINIMUM_HOST_TOKENS MIN_LOAD_TOKENS
bash infra/container/run_kv_movement_interference_reference.sh "$MODEL"
