#!/usr/bin/env bash
set -euo pipefail

# Host-side paired hardware probe. The controller and driver remain native to
# the host; each clean SGLang backend runs only inside Docker. This command
# intentionally carries no frontend priority field.

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DIRECT_ROOT="${REPO_ROOT}/sglang_direct_kv"
BACKEND_RUNTIME_PROFILE="${BACKEND_RUNTIME_PROFILE:-nvidia_standard}"
PROFILE_PATH="${BACKEND_RUNTIME_PROFILE_PATH:-${REPO_ROOT}/configs/backend_runtimes/${BACKEND_RUNTIME_PROFILE}.json}"
SGLANG_DOCKER_IMAGE="${SGLANG_DOCKER_IMAGE:-}"
AGENTIC_MODEL_CACHE="${AGENTIC_MODEL_CACHE:-}"
REPORT_LABEL="${REPORT_LABEL:-hardware_kv_movement_$(date +%Y%m%d_%H%M%S)}"
SAMPLE_SET_ID="${SAMPLE_SET_ID:-${REPORT_LABEL}_samples}"
TRIALS="${TRIALS:-4}"
SEED="${SEED:-7}"
WORKLOAD_ID="${WORKLOAD_ID:-hardware_kv_movement_v1}"
DONOR_PROMPT_TOKENS="${DONOR_PROMPT_TOKENS:-4090}"
MIN_LOAD_TOKENS="${MIN_LOAD_TOKENS:-1}"

if [[ ! -f "${PROFILE_PATH}" ]]; then
  echo "Backend runtime profile not found: ${PROFILE_PATH}" >&2
  exit 2
fi
if [[ -z "${SGLANG_DOCKER_IMAGE}" ]]; then
  echo "Set SGLANG_DOCKER_IMAGE to the pinned backend image." >&2
  exit 2
fi
if [[ -z "${AGENTIC_MODEL_CACHE}" || ! -d "${AGENTIC_MODEL_CACHE}" ]]; then
  echo "Set AGENTIC_MODEL_CACHE to an existing host model-cache directory." >&2
  exit 2
fi

profile_value() {
  python3 - "${PROFILE_PATH}" "$1" <<'PY'
import json
import sys
value = json.load(open(sys.argv[1], encoding="utf-8")).get(sys.argv[2], "")
print(" ".join(value) if isinstance(value, list) else value)
PY
}

PROFILE_ID="$(profile_value profile_id)"
HARDWARE_PROFILE="${HARDWARE_PROFILE:-$(profile_value hardware_profile)}"
MODEL_CACHE_MOUNT="$(profile_value model_cache_mount)"
GPU_ARGS="$(profile_value gpu_runtime_args)"
RUN_ROOT="${DIRECT_ROOT}/artifacts/results/hardware/${REPORT_LABEL}"
RUNTIME_DIR="${RUN_ROOT}/runtime"
BACKEND_RUNTIME_CONTRACT_OUT="${RUNTIME_DIR}/backend_runtime.json"
MANIFEST_PATH="${RUN_ROOT}/run_manifest.json"
COMMAND_PATH="${RUN_ROOT}/command.sh"
SERVER_PID=""

cleanup_backend() {
  if [[ -n "${SERVER_PID}" ]] && kill -0 "${SERVER_PID}" 2>/dev/null; then
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
  SERVER_PID=""
}
trap cleanup_backend EXIT

mkdir -p "${RUNTIME_DIR}"
mount_args=(
  -v "${AGENTIC_MODEL_CACHE}:${MODEL_CACHE_MOUNT}"
  -e "HF_HOME=${MODEL_CACHE_MOUNT}"
)
export SGLANG_DOCKER_EXTRA_ARGS="$(printf '%q ' "${mount_args[@]}") ${SGLANG_DOCKER_EXTRA_ARGS:-}"
export SGLANG_DOCKER_GPU_ARGS="${SGLANG_DOCKER_GPU_ARGS:-${GPU_ARGS}}"
export SGLANG_DOCKER_IMAGE BACKEND_RUNTIME_PROFILE HARDWARE_PROFILE
export BACKEND_RUNTIME_CONTRACT_OUT

if [[ -f "${DIRECT_ROOT}/.venv/bin/activate" ]]; then
  # shellcheck source=/dev/null
  source "${DIRECT_ROOT}/.venv/bin/activate"
fi

PACKAGE_PYTHONPATH=""
for package_src in "${REPO_ROOT}"/packages/*/src; do
  [[ -d "${package_src}" ]] || continue
  PACKAGE_PYTHONPATH="${PACKAGE_PYTHONPATH:+${PACKAGE_PYTHONPATH}:}${package_src}"
done
export PYTHONPATH="${PACKAGE_PYTHONPATH}:${PYTHONPATH:-}"

echo "KV movement interference reference"
echo "  profile: ${PROFILE_ID}"
echo "  hardware: ${HARDWARE_PROFILE}"
echo "  image: ${SGLANG_DOCKER_IMAGE}"
echo "  trials: ${TRIALS}; seed: ${SEED}; sample set: ${SAMPLE_SET_ID}"

"${SCRIPT_DIR}/probe_sglang_runtime.sh"
BACKEND_VERSION="$(python3 - "${BACKEND_RUNTIME_CONTRACT_OUT}" <<'PY'
import json
import sys
print(json.load(open(sys.argv[1], encoding="utf-8"))["backend_version"])
PY
)"

cat >"${COMMAND_PATH}" <<EOF
# Reproducible paired hardware probe; generated by ${0}.
MODEL=${MODEL@Q}
BACKEND_RUNTIME_PROFILE=${BACKEND_RUNTIME_PROFILE@Q}
SGLANG_DOCKER_IMAGE=${SGLANG_DOCKER_IMAGE@Q}
AGENTIC_MODEL_CACHE=${AGENTIC_MODEL_CACHE@Q}
REPORT_LABEL=${REPORT_LABEL@Q}
SAMPLE_SET_ID=${SAMPLE_SET_ID@Q}
TRIALS=${TRIALS@Q}
SEED=${SEED@Q}
bash infra/container/run_kv_movement_interference_reference.sh "\$MODEL"
EOF
chmod +x "${COMMAND_PATH}"

wait_for_server() {
  local deadline=$((SECONDS + 240))
  until curl --silent --show-error --fail http://127.0.0.1:30000/v1/models >/dev/null; do
    if [[ -n "${SERVER_PID}" ]] && ! kill -0 "${SERVER_PID}" 2>/dev/null; then
      echo "SGLang exited during startup; inspect ${1}/server.log" >&2
      return 1
    fi
    if (( SECONDS >= deadline )); then
      echo "SGLang server did not become ready; inspect ${1}/server.log" >&2
      return 1
    fi
    sleep 2
  done
}

verify_trace_install() {
  local trace_path="$1"
  python3 - "${trace_path}" <<'PY'
import json
import sys
path = sys.argv[1]
rows = []
try:
    rows = [json.loads(line) for line in open(path, encoding="utf-8") if line.strip()]
except FileNotFoundError:
    raise SystemExit(f"Trace is missing: {path}")
if not any(row.get("event") == "trace.install.summary" for row in rows):
    raise SystemExit("Trace hook installation summary is missing; refusing to trust this run.")
if not any(row.get("event") == "agentic_kv.prepare_prefix.result" for row in rows):
    raise SystemExit("Prepared-prefix control was not observed in the backend trace.")
PY
}

run_condition() {
  local condition="$1"
  local condition_dir="${RUN_ROOT}/${condition}"
  local combined_trace="${condition_dir}/backend_trace.jsonl"
  rm -rf "${condition_dir}"
  mkdir -p "${condition_dir}"
  : >"${combined_trace}"

  for ((sample_index = 0; sample_index < TRIALS; sample_index++)); do
    local trial_dir="${condition_dir}/trial_$(printf '%03d' "${sample_index}")"
    local trace_path="${trial_dir}/backend_trace.jsonl"
    mkdir -p "${trial_dir}"
    echo "Starting clean ${condition} backend for sample ${sample_index}/${TRIALS}..."
    (
      cd "${DIRECT_ROOT}"
      export AGENTIC_KV_TRACE_ENABLE=1
      export AGENTIC_KV_TRACE_PATH="${trace_path}"
      # The JSONL trace itself is the authoritative install/evidence record.
      export AGENTIC_KV_TRACE_INSTALL_REPORT_PATH=""
      export AGENTIC_KV_TRACE_SCHEDULER=1
      export AGENTIC_KV_TRACE_KV_POOL=1
      export AGENTIC_KV_PREPARE_CONTROL_ENABLE=1
      export AGENTIC_KV_PREPARE_CONTROL_HOST=127.0.0.1
      export AGENTIC_KV_PREPARE_CONTROL_PORT=31991
      export AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS=10000
      export HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-8}"
      # Qwen2.5-Coder-7B weights need more than half of the 24 GB A10G before
      # SGLang can allocate its static pool; callers can still override this.
      export MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.70}"
      bash scripts/run_sglang_hicache_server.sh "${MODEL}"
    ) >"${trial_dir}/server.log" 2>&1 &
    SERVER_PID="$!"
    wait_for_server "${trial_dir}"

    append_args=()
    if (( sample_index > 0 )); then
      append_args=(--append)
    fi
    python3 -m agentic_experiments.runners.run_kv_movement_interference \
      --condition "${condition}" \
      --run-id "${REPORT_LABEL}_${condition}" \
      --sample-set-id "${SAMPLE_SET_ID}" \
      --out-dir "${condition_dir}" \
      --model "${MODEL}" \
      --hardware-profile "${HARDWARE_PROFILE}" \
      --backend-version "${BACKEND_VERSION}" \
      --workload-id "${WORKLOAD_ID}" \
      --seed "${SEED}" \
      --donor-prompt-tokens "${DONOR_PROMPT_TOKENS}" \
      --min-load-tokens "${MIN_LOAD_TOKENS}" \
      --trials 1 \
      --sample-offset "${sample_index}" \
      "${append_args[@]}"
    verify_trace_install "${trace_path}"
    cat "${trace_path}" >>"${combined_trace}"
    cleanup_backend
  done
}

run_condition control
run_condition interference

python3 -m agentic_reports.builders.build_hardware_kv_movement_report \
  --control "${RUN_ROOT}/control/probe_run.json" \
  --interference "${RUN_ROOT}/interference/probe_run.json" \
  --control-backend-trace "${RUN_ROOT}/control/backend_trace.jsonl" \
  --interference-backend-trace "${RUN_ROOT}/interference/backend_trace.jsonl" \
  --out "${RUN_ROOT}/hardware_kv_movement_report.html" \
  --summary-out "${RUN_ROOT}/hardware_kv_movement_summary.json"

workload_json="$(python3 - <<PY
import json
print(json.dumps({
  "workload_id": "${WORKLOAD_ID}", "sample_set_id": "${SAMPLE_SET_ID}",
  "trials": int("${TRIALS}"), "seed": int("${SEED}"),
  "frontend_priority": "none", "conditions": ["control", "interference"],
}))
PY
)"
python3 "${REPO_ROOT}/scripts/create_run_manifest.py" \
  --out "${MANIFEST_PATH}" \
  --run-id "${REPORT_LABEL}" \
  --experiment "kv_movement_interference" \
  --model "${MODEL}" \
  --hardware-profile "${HARDWARE_PROFILE}" \
  --runtime-contract "${BACKEND_RUNTIME_CONTRACT_OUT}" \
  --workload-json "${workload_json}" \
  --instrumentation "lightweight_backend_trace" \
  --instrumentation "prepared_prefix_control" \
  --artifact "command=${COMMAND_PATH}" \
  --artifact "control_probe=${RUN_ROOT}/control/probe_run.json" \
  --artifact "interference_probe=${RUN_ROOT}/interference/probe_run.json" \
  --artifact "control_trace=${RUN_ROOT}/control/backend_trace.jsonl" \
  --artifact "interference_trace=${RUN_ROOT}/interference/backend_trace.jsonl" \
  --artifact "summary=${RUN_ROOT}/hardware_kv_movement_summary.json" \
  --artifact "report=${RUN_ROOT}/hardware_kv_movement_report.html" \
  --completion-status complete

echo "Complete: ${RUN_ROOT}/hardware_kv_movement_report.html"
