#!/usr/bin/env bash
set -euo pipefail

# Host-side, equal-priority hardware probe. Each sample gets a clean SGLang
# container; only the timing of one native host-to-device KV reload changes.

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DIRECT_ROOT="${REPO_ROOT}/sglang_direct_kv"
BACKEND_RUNTIME_PROFILE="${BACKEND_RUNTIME_PROFILE:-nvidia_standard}"
PROFILE_PATH="${BACKEND_RUNTIME_PROFILE_PATH:-${REPO_ROOT}/configs/backend_runtimes/${BACKEND_RUNTIME_PROFILE}.json}"
SGLANG_DOCKER_IMAGE="${SGLANG_DOCKER_IMAGE:-}"
AGENTIC_MODEL_CACHE="${AGENTIC_MODEL_CACHE:-}"
REPORT_LABEL="${REPORT_LABEL:-sustained_decode_kv_overlap_$(date +%Y%m%d_%H%M%S)}"
SAMPLE_SET_ID="${SAMPLE_SET_ID:-${REPORT_LABEL}_samples}"
TRIALS="${TRIALS:-1}"
SEED="${SEED:-7}"
WORKLOAD_ID="${WORKLOAD_ID:-sustained_decode_kv_overlap_v1}"
DECODE_TOKENS="${DECODE_TOKENS:-256}"
WARMUP_CHUNKS="${WARMUP_CHUNKS:-24}"
MINIMUM_OVERLAP_INTERVALS="${MINIMUM_OVERLAP_INTERVALS:-1}"
DONOR_PROMPT_TOKENS="${DONOR_PROMPT_TOKENS:-4090}"
EVICTION_PROMPT_TOKENS="${EVICTION_PROMPT_TOKENS:-8192}"
EVICTION_ROUNDS="${EVICTION_ROUNDS:-8}"
MINIMUM_HOST_TOKENS="${MINIMUM_HOST_TOKENS:-512}"
DEVICE_FREE_TOKENS="${DEVICE_FREE_TOKENS:-0}"
MIN_LOAD_TOKENS="${MIN_LOAD_TOKENS:-}"

if [[ ! -f "${PROFILE_PATH}" ]]; then
  echo "Backend runtime profile not found: ${PROFILE_PATH}" >&2
  exit 2
fi
if [[ -z "${SGLANG_DOCKER_IMAGE}" ]]; then
  echo "Set SGLANG_DOCKER_IMAGE to the pinned backend image." >&2
  exit 2
fi
if [[ -z "${AGENTIC_MODEL_CACHE}" || ! -d "${AGENTIC_MODEL_CACHE}" ]]; then
  echo "Set AGENTIC_MODEL_CACHE to an existing host model-cache directory." >&2
  exit 2
fi

profile_value() {
  python3 - "${PROFILE_PATH}" "$1" <<'PY'
import json
import sys
value = json.load(open(sys.argv[1], encoding="utf-8")).get(sys.argv[2], "")
print(" ".join(value) if isinstance(value, list) else value)
PY
}

PROFILE_ID="$(profile_value profile_id)"
HARDWARE_PROFILE="${HARDWARE_PROFILE:-$(profile_value hardware_profile)}"
MODEL_CACHE_MOUNT="$(profile_value model_cache_mount)"
GPU_ARGS="$(profile_value gpu_runtime_args)"
RUN_ROOT="${DIRECT_ROOT}/artifacts/results/hardware/${REPORT_LABEL}"
RUNTIME_DIR="${RUN_ROOT}/runtime"
BACKEND_RUNTIME_CONTRACT_OUT="${RUNTIME_DIR}/backend_runtime.json"
MANIFEST_PATH="${RUN_ROOT}/run_manifest.json"
COMMAND_PATH="${RUN_ROOT}/command.sh"
SERVER_PID=""

cleanup_backend() {
  if [[ -n "${SERVER_PID}" ]] && kill -0 "${SERVER_PID}" 2>/dev/null; then
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
  SERVER_PID=""
}
trap cleanup_backend EXIT

mkdir -p "${RUNTIME_DIR}"
mount_args=(
  -v "${AGENTIC_MODEL_CACHE}:${MODEL_CACHE_MOUNT}"
  -e "HF_HOME=${MODEL_CACHE_MOUNT}"
)
export SGLANG_DOCKER_EXTRA_ARGS="$(printf '%q ' "${mount_args[@]}") ${SGLANG_DOCKER_EXTRA_ARGS:-}"
export SGLANG_DOCKER_GPU_ARGS="${SGLANG_DOCKER_GPU_ARGS:-${GPU_ARGS}}"
export SGLANG_DOCKER_IMAGE BACKEND_RUNTIME_PROFILE HARDWARE_PROFILE
export BACKEND_RUNTIME_CONTRACT_OUT

if [[ -f "${DIRECT_ROOT}/.venv/bin/activate" ]]; then
  # shellcheck source=/dev/null
  source "${DIRECT_ROOT}/.venv/bin/activate"
fi

PACKAGE_PYTHONPATH=""
for package_src in "${REPO_ROOT}"/packages/*/src; do
  [[ -d "${package_src}" ]] || continue
  PACKAGE_PYTHONPATH="${PACKAGE_PYTHONPATH:+${PACKAGE_PYTHONPATH}:}${package_src}"
done
export PYTHONPATH="${PACKAGE_PYTHONPATH}:${PYTHONPATH:-}"

echo "Sustained decode KV-overlap reference"
echo "  profile: ${PROFILE_ID}"
echo "  hardware: ${HARDWARE_PROFILE}"
echo "  image: ${SGLANG_DOCKER_IMAGE}"
echo "  trials per condition: ${TRIALS}; seed: ${SEED}"

"${SCRIPT_DIR}/probe_sglang_runtime.sh"
BACKEND_VERSION="$(python3 - "${BACKEND_RUNTIME_CONTRACT_OUT}" <<'PY'
import json
import sys
print(json.load(open(sys.argv[1], encoding="utf-8"))["backend_version"])
PY
)"
BACKEND_ADAPTER="$(python3 - "${BACKEND_RUNTIME_CONTRACT_OUT}" <<'PY'
import json
import sys
print(json.load(open(sys.argv[1], encoding="utf-8"))["adapter"])
PY
)"

cat >"${COMMAND_PATH}" <<EOF
# Reproducible sustained-decode overlap probe; generated by ${0}.
MODEL=${MODEL@Q}
BACKEND_RUNTIME_PROFILE=${BACKEND_RUNTIME_PROFILE@Q}
SGLANG_DOCKER_IMAGE=${SGLANG_DOCKER_IMAGE@Q}
AGENTIC_MODEL_CACHE=${AGENTIC_MODEL_CACHE@Q}
REPORT_LABEL=${REPORT_LABEL@Q}
SAMPLE_SET_ID=${SAMPLE_SET_ID@Q}
TRIALS=${TRIALS@Q}
SEED=${SEED@Q}
DECODE_TOKENS=${DECODE_TOKENS@Q}
WARMUP_CHUNKS=${WARMUP_CHUNKS@Q}
MINIMUM_OVERLAP_INTERVALS=${MINIMUM_OVERLAP_INTERVALS@Q}
DONOR_PROMPT_TOKENS=${DONOR_PROMPT_TOKENS@Q}
EVICTION_PROMPT_TOKENS=${EVICTION_PROMPT_TOKENS@Q}
EVICTION_ROUNDS=${EVICTION_ROUNDS@Q}
MINIMUM_HOST_TOKENS=${MINIMUM_HOST_TOKENS@Q}
DEVICE_FREE_TOKENS=${DEVICE_FREE_TOKENS@Q}
MIN_LOAD_TOKENS=${MIN_LOAD_TOKENS@Q}
export BACKEND_RUNTIME_PROFILE SGLANG_DOCKER_IMAGE AGENTIC_MODEL_CACHE REPORT_LABEL SAMPLE_SET_ID TRIALS SEED
export DECODE_TOKENS WARMUP_CHUNKS MINIMUM_OVERLAP_INTERVALS DONOR_PROMPT_TOKENS EVICTION_PROMPT_TOKENS EVICTION_ROUNDS
export MINIMUM_HOST_TOKENS DEVICE_FREE_TOKENS MIN_LOAD_TOKENS
bash infra/container/run_sustained_decode_kv_overlap_reference.sh "\$MODEL"
EOF
chmod +x "${COMMAND_PATH}"

wait_for_server() {
  local trial_dir="$1"
  local deadline=$((SECONDS + 240))
  until curl --silent --show-error --fail http://127.0.0.1:30000/v1/models >/dev/null; do
    if [[ -n "${SERVER_PID}" ]] && ! kill -0 "${SERVER_PID}" 2>/dev/null; then
      echo "SGLang exited during startup; inspect ${trial_dir}/server.log" >&2
      return 1
    fi
    if (( SECONDS >= deadline )); then
      echo "SGLang server did not become ready; inspect ${trial_dir}/server.log" >&2
      return 1
    fi
    sleep 2
  done
}

run_condition() {
  local condition="$1"
  local condition_dir="${RUN_ROOT}/${condition}"
  local combined_trace="${condition_dir}/backend_trace.jsonl"
  rm -rf "${condition_dir}"
  mkdir -p "${condition_dir}"
  : >"${combined_trace}"

  for ((sample_index = 0; sample_index < TRIALS; sample_index++)); do
    local trial_dir="${condition_dir}/trial_$(printf '%03d' "${sample_index}")"
    local trace_path="${trial_dir}/backend_trace.jsonl"
    local copy_path="${trial_dir}/kv_copy_telemetry.jsonl"
    mkdir -p "${trial_dir}"
    echo "Starting clean ${condition} backend for sample ${sample_index}/${TRIALS}..."
    (
      cd "${DIRECT_ROOT}"
      export AGENTIC_KV_TRACE_ENABLE=1
      export AGENTIC_KV_TRACE_PATH="${trace_path}"
      export AGENTIC_KV_TRACE_INSTALL_REPORT_PATH=""
      profile_values="$(python3 -m agentic_backends.sglang.instrumentation_profiles copy_timing --shell)"
      while IFS='=' read -r name value; do
        [[ -z "${name}" || "${name}" == *_DEFAULT ]] && continue
        printf -v "${name}" '%s' "${value}"
        export "${name}"
      done <<< "${profile_values}"
      export AGENTIC_KV_COPY_TELEMETRY_PATH="${copy_path}"
      export AGENTIC_KV_PREPARE_CONTROL_ENABLE=1
      export AGENTIC_KV_PREPARE_CONTROL_HOST=127.0.0.1
      export AGENTIC_KV_PREPARE_CONTROL_PORT=31991
      export AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS=30000
      export HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-8}"
      export MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.70}"
      bash scripts/run_sglang_hicache_server.sh "${MODEL}"
    ) >"${trial_dir}/server.log" 2>&1 &
    SERVER_PID="$!"
    wait_for_server "${trial_dir}"
    python3 -m agentic_backends.sglang.trace_contract \
      --adapter "${BACKEND_ADAPTER}" --profile copy_timing --installation-only \
      --trace "${trace_path}" --out "${trial_dir}/hook_installation_audit.json"

    append_args=()
    if (( sample_index > 0 )); then
      append_args=(--append)
    fi
    load_threshold_args=()
    if [[ -n "${MIN_LOAD_TOKENS}" ]]; then
      load_threshold_args=(--min-load-tokens "${MIN_LOAD_TOKENS}")
    fi
    python3 -m agentic_experiments.runners.run_sustained_decode_kv_overlap \
      --condition "${condition}" \
      --run-id "${REPORT_LABEL}_${condition}" \
      --sample-set-id "${SAMPLE_SET_ID}" \
      --out-dir "${condition_dir}" \
      --model "${MODEL}" \
      --hardware-profile "${HARDWARE_PROFILE}" \
      --backend-version "${BACKEND_VERSION}" \
      --workload-id "${WORKLOAD_ID}" \
      --seed "${SEED}" \
      --decode-tokens "${DECODE_TOKENS}" \
      --warmup-chunks "${WARMUP_CHUNKS}" \
      --minimum-overlap-intervals "${MINIMUM_OVERLAP_INTERVALS}" \
      --donor-prompt-tokens "${DONOR_PROMPT_TOKENS}" \
      --eviction-prompt-tokens "${EVICTION_PROMPT_TOKENS}" \
      --eviction-rounds "${EVICTION_ROUNDS}" \
      --minimum-host-tokens "${MINIMUM_HOST_TOKENS}" \
      --device-free-tokens "${DEVICE_FREE_TOKENS}" \
      --trials 1 \
      --sample-offset "${sample_index}" \
      "${load_threshold_args[@]}" \
      "${append_args[@]}"
    gate_args=()
    if [[ "${condition}" == "decode_control" ]]; then
      gate_args=(--installation-only)
    fi
    python3 -m agentic_backends.sglang.trace_contract \
      --adapter "${BACKEND_ADAPTER}" --profile copy_timing \
      --trace "${trace_path}" --out "${trial_dir}/instrumentation_audit.json" \
      --events-out "${trial_dir}/normalized_backend_evidence.jsonl" \
      --export-signal request.accepted --export-signal kv.load_gpu --export-signal kv.layer_copy \
      "${gate_args[@]}"
    python3 -m agentic_hardware_probes.backend_evidence \
      --probe "${condition_dir}/probe_run.json" \
      --sample-id "trial_$(printf '%03d' "${sample_index}")" \
      --events "${trial_dir}/normalized_backend_evidence.jsonl" \
      --out "${trial_dir}/backend_evidence_join.json"
    cat "${trace_path}" >>"${combined_trace}"
    cleanup_backend
  done
}

run_condition decode_control
run_condition non_overlap_reload
run_condition direct_overlap_reload

python3 -m agentic_reports.builders.build_sustained_decode_kv_overlap_report \
  --control "${RUN_ROOT}/decode_control/probe_run.json" \
  --non-overlap "${RUN_ROOT}/non_overlap_reload/probe_run.json" \
  --direct-overlap "${RUN_ROOT}/direct_overlap_reload/probe_run.json" \
  --out "${RUN_ROOT}/sustained_decode_kv_overlap_report.html" \
  --summary-out "${RUN_ROOT}/sustained_decode_kv_overlap_summary.json"

workload_json="$(python3 - <<PY
import json
print(json.dumps({
  "workload_id": "${WORKLOAD_ID}", "sample_set_id": "${SAMPLE_SET_ID}",
  "trials_per_condition": int("${TRIALS}"), "seed": int("${SEED}"),
  "frontend_priority": "none",
  "conditions": ["decode_control", "non_overlap_reload", "direct_overlap_reload"],
  "decode_tokens": int("${DECODE_TOKENS}"), "warmup_chunks": int("${WARMUP_CHUNKS}"),
  "minimum_overlap_intervals": int("${MINIMUM_OVERLAP_INTERVALS}"),
  "donor_prompt_tokens": int("${DONOR_PROMPT_TOKENS}"),
  "device_free_tokens": int("${DEVICE_FREE_TOKENS}"),
}))
PY
)"
python3 "${REPO_ROOT}/scripts/create_run_manifest.py" \
  --out "${MANIFEST_PATH}" \
  --run-id "${REPORT_LABEL}" \
  --experiment "sustained_decode_kv_overlap" \
  --model "${MODEL}" \
  --hardware-profile "${HARDWARE_PROFILE}" \
  --runtime-contract "${BACKEND_RUNTIME_CONTRACT_OUT}" \
  --workload-json "${workload_json}" \
  --instrumentation "lightweight_backend_trace" \
  --instrumentation "cuda_event_load_status" \
  --instrumentation "streamed_decode_timing" \
  --artifact "command=${COMMAND_PATH}" \
  --artifact "control_probe=${RUN_ROOT}/decode_control/probe_run.json" \
  --artifact "non_overlap_probe=${RUN_ROOT}/non_overlap_reload/probe_run.json" \
  --artifact "direct_overlap_probe=${RUN_ROOT}/direct_overlap_reload/probe_run.json" \
  --artifact "summary=${RUN_ROOT}/sustained_decode_kv_overlap_summary.json" \
  --artifact "report=${RUN_ROOT}/sustained_decode_kv_overlap_report.html" \
  --completion-status complete

echo "Complete: ${RUN_ROOT}/sustained_decode_kv_overlap_report.html"
