#!/usr/bin/env bash
set -euo pipefail

# Equal-frontend-semantics hardware probe. Each sample/condition gets a clean
# SGLang container. Conditions differ only in the number of native KV reloads
# issued after decode has started.

MODEL="${1:-Qwen/Qwen2.5-Coder-7B-Instruct}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DIRECT_ROOT="${REPO_ROOT}/sglang_direct_kv"
BACKEND_RUNTIME_PROFILE="${BACKEND_RUNTIME_PROFILE:-nvidia_standard}"
PROFILE_PATH="${BACKEND_RUNTIME_PROFILE_PATH:-${REPO_ROOT}/configs/backend_runtimes/${BACKEND_RUNTIME_PROFILE}.json}"
SGLANG_DOCKER_IMAGE="${SGLANG_DOCKER_IMAGE:-}"
AGENTIC_MODEL_CACHE="${AGENTIC_MODEL_CACHE:-}"
REPORT_LABEL="${REPORT_LABEL:-sustained_kv_pressure_$(date +%Y%m%d_%H%M%S)}"
SAMPLE_SET_ID="${SAMPLE_SET_ID:-${REPORT_LABEL}_samples}"
TRIALS="${TRIALS:-1}"
CONDITIONS="${CONDITIONS:-decode_control single_reload sustained_reload}"
SEED="${SEED:-7}"
WORKLOAD_ID="${WORKLOAD_ID:-sustained_kv_pressure_v1}"
DECODE_TOKENS="${DECODE_TOKENS:-256}"
WARMUP_CHUNKS="${WARMUP_CHUNKS:-24}"
DONOR_COUNT="${DONOR_COUNT:-8}"
DONOR_PROMPT_TOKENS="${DONOR_PROMPT_TOKENS:-4090}"
EVICTION_PROMPT_TOKENS="${EVICTION_PROMPT_TOKENS:-8192}"
EVICTION_ROUNDS="${EVICTION_ROUNDS:-8}"
MINIMUM_HOST_TOKENS="${MINIMUM_HOST_TOKENS:-512}"
DEVICE_FREE_TOKENS="${DEVICE_FREE_TOKENS:-40000}"
MINIMUM_TOTAL_CUDA_LOAD_MS="${MINIMUM_TOTAL_CUDA_LOAD_MS:-500}"
MAXIMUM_INTER_LOAD_GAP_MS="${MAXIMUM_INTER_LOAD_GAP_MS:-250}"
MIN_LOAD_TOKENS="${MIN_LOAD_TOKENS:-}"
HICACHE_SIZE_GB="${HICACHE_SIZE_GB:-8}"
MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.80}"

if [[ ! -f "${PROFILE_PATH}" ]]; then
  echo "Backend runtime profile not found: ${PROFILE_PATH}" >&2
  exit 2
fi
if [[ -z "${SGLANG_DOCKER_IMAGE}" ]]; then
  echo "Set SGLANG_DOCKER_IMAGE to the pinned backend image." >&2
  exit 2
fi
if [[ -z "${AGENTIC_MODEL_CACHE}" || ! -d "${AGENTIC_MODEL_CACHE}" ]]; then
  echo "Set AGENTIC_MODEL_CACHE to an existing host model-cache directory." >&2
  exit 2
fi

profile_value() {
  python3 - "${PROFILE_PATH}" "$1" <<'PY'
import json
import sys
value = json.load(open(sys.argv[1], encoding="utf-8")).get(sys.argv[2], "")
print(" ".join(value) if isinstance(value, list) else value)
PY
}

PROFILE_ID="$(profile_value profile_id)"
HARDWARE_PROFILE="${HARDWARE_PROFILE:-$(profile_value hardware_profile)}"
MODEL_CACHE_MOUNT="$(profile_value model_cache_mount)"
GPU_ARGS="$(profile_value gpu_runtime_args)"
RUN_ROOT="${DIRECT_ROOT}/artifacts/results/hardware/${REPORT_LABEL}"
RUNTIME_DIR="${RUN_ROOT}/runtime"
BACKEND_RUNTIME_CONTRACT_OUT="${RUNTIME_DIR}/backend_runtime.json"
MANIFEST_PATH="${RUN_ROOT}/run_manifest.json"
COMMAND_PATH="${RUN_ROOT}/command.sh"
SERVER_PID=""

cleanup_backend() {
  if [[ -n "${SERVER_PID}" ]] && kill -0 "${SERVER_PID}" 2>/dev/null; then
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
  SERVER_PID=""
}
trap cleanup_backend EXIT

mkdir -p "${RUNTIME_DIR}"
mount_args=(
  -v "${AGENTIC_MODEL_CACHE}:${MODEL_CACHE_MOUNT}"
  -e "HF_HOME=${MODEL_CACHE_MOUNT}"
)
export SGLANG_DOCKER_EXTRA_ARGS="$(printf '%q ' "${mount_args[@]}") ${SGLANG_DOCKER_EXTRA_ARGS:-}"
export SGLANG_DOCKER_GPU_ARGS="${SGLANG_DOCKER_GPU_ARGS:-${GPU_ARGS}}"
export SGLANG_DOCKER_IMAGE BACKEND_RUNTIME_PROFILE HARDWARE_PROFILE
export BACKEND_RUNTIME_CONTRACT_OUT

if [[ -f "${DIRECT_ROOT}/.venv/bin/activate" ]]; then
  # shellcheck source=/dev/null
  source "${DIRECT_ROOT}/.venv/bin/activate"
fi

PACKAGE_PYTHONPATH=""
for package_src in "${REPO_ROOT}"/packages/*/src; do
  [[ -d "${package_src}" ]] || continue
  PACKAGE_PYTHONPATH="${PACKAGE_PYTHONPATH:+${PACKAGE_PYTHONPATH}:}${package_src}"
done
export PYTHONPATH="${PACKAGE_PYTHONPATH}:${PYTHONPATH:-}"

echo "Sustained KV pressure reference"
echo "  profile: ${PROFILE_ID}"
echo "  hardware: ${HARDWARE_PROFILE}"
echo "  image: ${SGLANG_DOCKER_IMAGE}"
echo "  donors: ${DONOR_COUNT}; trials per condition: ${TRIALS}; seed: ${SEED}"

"${SCRIPT_DIR}/probe_sglang_runtime.sh"
BACKEND_VERSION="$(python3 - "${BACKEND_RUNTIME_CONTRACT_OUT}" <<'PY'
import json
import sys
print(json.load(open(sys.argv[1], encoding="utf-8"))["backend_version"])
PY
)"

cat >"${COMMAND_PATH}" <<EOF
# Reproducible sustained-KV-pressure probe; generated by ${0}.
MODEL=${MODEL@Q}
BACKEND_RUNTIME_PROFILE=${BACKEND_RUNTIME_PROFILE@Q}
SGLANG_DOCKER_IMAGE=${SGLANG_DOCKER_IMAGE@Q}
AGENTIC_MODEL_CACHE=${AGENTIC_MODEL_CACHE@Q}
REPORT_LABEL=${REPORT_LABEL@Q}
SAMPLE_SET_ID=${SAMPLE_SET_ID@Q}
TRIALS=${TRIALS@Q}
CONDITIONS=${CONDITIONS@Q}
SEED=${SEED@Q}
DECODE_TOKENS=${DECODE_TOKENS@Q}
WARMUP_CHUNKS=${WARMUP_CHUNKS@Q}
DONOR_COUNT=${DONOR_COUNT@Q}
DONOR_PROMPT_TOKENS=${DONOR_PROMPT_TOKENS@Q}
EVICTION_PROMPT_TOKENS=${EVICTION_PROMPT_TOKENS@Q}
EVICTION_ROUNDS=${EVICTION_ROUNDS@Q}
MINIMUM_HOST_TOKENS=${MINIMUM_HOST_TOKENS@Q}
DEVICE_FREE_TOKENS=${DEVICE_FREE_TOKENS@Q}
MINIMUM_TOTAL_CUDA_LOAD_MS=${MINIMUM_TOTAL_CUDA_LOAD_MS@Q}
MAXIMUM_INTER_LOAD_GAP_MS=${MAXIMUM_INTER_LOAD_GAP_MS@Q}
MIN_LOAD_TOKENS=${MIN_LOAD_TOKENS@Q}
HICACHE_SIZE_GB=${HICACHE_SIZE_GB@Q}
MEM_FRACTION_STATIC=${MEM_FRACTION_STATIC@Q}
export BACKEND_RUNTIME_PROFILE SGLANG_DOCKER_IMAGE AGENTIC_MODEL_CACHE REPORT_LABEL SAMPLE_SET_ID TRIALS CONDITIONS SEED
export DECODE_TOKENS WARMUP_CHUNKS DONOR_COUNT DONOR_PROMPT_TOKENS EVICTION_PROMPT_TOKENS EVICTION_ROUNDS
export MINIMUM_HOST_TOKENS DEVICE_FREE_TOKENS MINIMUM_TOTAL_CUDA_LOAD_MS MAXIMUM_INTER_LOAD_GAP_MS MIN_LOAD_TOKENS
export HICACHE_SIZE_GB MEM_FRACTION_STATIC
bash infra/container/run_sustained_kv_pressure_reference.sh "\$MODEL"
EOF
chmod +x "${COMMAND_PATH}"

wait_for_server() {
  local trial_dir="$1"
  local deadline=$((SECONDS + 240))
  until curl --silent --show-error --fail http://127.0.0.1:30000/v1/models >/dev/null; do
    if [[ -n "${SERVER_PID}" ]] && ! kill -0 "${SERVER_PID}" 2>/dev/null; then
      echo "SGLang exited during startup; inspect ${trial_dir}/server.log" >&2
      return 1
    fi
    if (( SECONDS >= deadline )); then
      echo "SGLang server did not become ready; inspect ${trial_dir}/server.log" >&2
      return 1
    fi
    sleep 2
  done
}

verify_trace_install() {
  local condition="$1"
  local trace_path="$2"
  python3 - "${condition}" "${trace_path}" "${DONOR_COUNT}" <<'PY'
import json
import sys

condition, path, donor_count = sys.argv[1], sys.argv[2], int(sys.argv[3])
rows = [json.loads(line) for line in open(path, encoding="utf-8") if line.strip()]
summaries = [row for row in rows if row.get("event") == "trace.install.summary"]
if not summaries:
    raise SystemExit("Trace hook installation summary is missing; refusing to trust this run.")
missing = summaries[-1].get("missing_required_hooks") or []
for name in (
    "HiCacheController.start_loading",
    "HiRadixCache.load_back",
    "MHATokenToKVPoolHost.load_to_device_per_layer",
):
    if any(name in item for item in missing):
        raise SystemExit(f"Required pressure hook is missing: {name}")
expected = {"decode_control": 0, "single_reload": 1, "sustained_reload": donor_count}[condition]
finished = [
    row for row in rows
    if row.get("event") == "agentic_kv.prepare_prefix.load_status" and row.get("status") == "finished"
]
if len(finished) != expected:
    raise SystemExit(f"Expected {expected} finished native loads, observed {len(finished)}")
if expected and not any(
    str(row.get("event") or "").endswith("hostpool.load_to_device_per_layer.end")
    for row in rows
):
    raise SystemExit("No host-to-device layer-copy event was captured.")
PY
}

start_backend_and_run() {
  local condition="$1"
  local sample_index="$2"
  local condition_dir="${RUN_ROOT}/${condition}"
  local trial_dir="${condition_dir}/trial_$(printf '%03d' "${sample_index}")"
  local trace_path="${trial_dir}/backend_trace.jsonl"
  local copy_path="${trial_dir}/kv_copy_telemetry.jsonl"
  mkdir -p "${trial_dir}"
  : >"${trace_path}"
  : >"${copy_path}"
  echo "Starting clean ${condition} backend for sample ${sample_index}/${TRIALS}..."
  (
    cd "${DIRECT_ROOT}"
    export AGENTIC_KV_TRACE_ENABLE=1
    export AGENTIC_KV_TRACE_PATH="${trace_path}"
    export AGENTIC_KV_TRACE_INSTALL_REPORT_PATH=""
    export AGENTIC_KV_TRACE_SCHEDULER=1
    export AGENTIC_KV_TRACE_KV_POOL=1
    export AGENTIC_KV_COPY_TELEMETRY_ENABLE=1
    export AGENTIC_KV_COPY_TELEMETRY_PATH="${copy_path}"
    export AGENTIC_KV_PREPARE_CONTROL_ENABLE=1
    export AGENTIC_KV_PREPARE_CONTROL_HOST=127.0.0.1
    export AGENTIC_KV_PREPARE_CONTROL_PORT=31991
    export AGENTIC_KV_PREPARE_WAIT_TIMEOUT_MS=30000
    export HICACHE_SIZE_GB MEM_FRACTION_STATIC
    bash scripts/run_sglang_hicache_server.sh "${MODEL}"
  ) >"${trial_dir}/server.log" 2>&1 &
  SERVER_PID="$!"
  wait_for_server "${trial_dir}"

  local append_args=()
  (( sample_index > 0 )) && append_args=(--append)
  local load_threshold_args=()
  [[ -n "${MIN_LOAD_TOKENS}" ]] && load_threshold_args=(--min-load-tokens "${MIN_LOAD_TOKENS}")
  python3 -m agentic_experiments.runners.run_sustained_kv_pressure \
    --condition "${condition}" \
    --run-id "${REPORT_LABEL}_${condition}" \
    --sample-set-id "${SAMPLE_SET_ID}" \
    --out-dir "${condition_dir}" \
    --model "${MODEL}" \
    --hardware-profile "${HARDWARE_PROFILE}" \
    --backend-version "${BACKEND_VERSION}" \
    --workload-id "${WORKLOAD_ID}" \
    --seed "${SEED}" \
    --decode-tokens "${DECODE_TOKENS}" \
    --warmup-chunks "${WARMUP_CHUNKS}" \
    --donor-count "${DONOR_COUNT}" \
    --donor-prompt-tokens "${DONOR_PROMPT_TOKENS}" \
    --eviction-prompt-tokens "${EVICTION_PROMPT_TOKENS}" \
    --eviction-rounds "${EVICTION_ROUNDS}" \
    --minimum-host-tokens "${MINIMUM_HOST_TOKENS}" \
    --device-free-tokens "${DEVICE_FREE_TOKENS}" \
    --minimum-total-cuda-load-ms "${MINIMUM_TOTAL_CUDA_LOAD_MS}" \
    --maximum-inter-load-gap-ms "${MAXIMUM_INTER_LOAD_GAP_MS}" \
    --trials 1 \
    --sample-offset "${sample_index}" \
    "${load_threshold_args[@]}" \
    "${append_args[@]}"
  verify_trace_install "${condition}" "${trace_path}"
  cat "${trace_path}" >>"${condition_dir}/backend_trace.jsonl"
  cleanup_backend
}

condition_enabled() {
  case " ${CONDITIONS} " in
    *" $1 "*) return 0 ;;
    *) return 1 ;;
  esac
}

for condition in decode_control single_reload sustained_reload; do
  condition_enabled "${condition}" || continue
  mkdir -p "${RUN_ROOT}/${condition}"
  : >"${RUN_ROOT}/${condition}/backend_trace.jsonl"
done

# Rotate order per paired sample to reduce order and temperature bias.
orders=(
  "decode_control single_reload sustained_reload"
  "single_reload sustained_reload decode_control"
  "sustained_reload decode_control single_reload"
)
for ((sample_index = 0; sample_index < TRIALS; sample_index++)); do
  read -r -a sample_order <<<"${orders[$((sample_index % 3))]}"
  for condition in "${sample_order[@]}"; do
    condition_enabled "${condition}" || continue
    start_backend_and_run "${condition}" "${sample_index}"
  done
done

python3 -m agentic_reports.builders.build_sustained_kv_pressure_report \
  --control "${RUN_ROOT}/decode_control/probe_run.json" \
  --single "${RUN_ROOT}/single_reload/probe_run.json" \
  --sustained "${RUN_ROOT}/sustained_reload/probe_run.json" \
  --out "${RUN_ROOT}/sustained_kv_pressure_report.html" \
  --summary-out "${RUN_ROOT}/sustained_kv_pressure_summary.json"

workload_json="$(python3 - <<PY
import json
print(json.dumps({
  "workload_id": "${WORKLOAD_ID}", "sample_set_id": "${SAMPLE_SET_ID}",
  "trials_per_condition": int("${TRIALS}"), "seed": int("${SEED}"),
  "frontend_priority": "none",
  "conditions": ["decode_control", "single_reload", "sustained_reload"],
  "decode_tokens": int("${DECODE_TOKENS}"), "warmup_chunks": int("${WARMUP_CHUNKS}"),
  "donor_count": int("${DONOR_COUNT}"), "donor_prompt_tokens": int("${DONOR_PROMPT_TOKENS}"),
  "device_free_tokens": int("${DEVICE_FREE_TOKENS}"),
  "minimum_total_cuda_load_ms": float("${MINIMUM_TOTAL_CUDA_LOAD_MS}"),
  "maximum_inter_load_gap_ms": float("${MAXIMUM_INTER_LOAD_GAP_MS}"),
  "hicache_size_gb": float("${HICACHE_SIZE_GB}"),
  "mem_fraction_static": float("${MEM_FRACTION_STATIC}"),
}))
PY
)"
python3 "${REPO_ROOT}/scripts/create_run_manifest.py" \
  --out "${MANIFEST_PATH}" \
  --run-id "${REPORT_LABEL}" \
  --experiment "sustained_kv_pressure" \
  --model "${MODEL}" \
  --hardware-profile "${HARDWARE_PROFILE}" \
  --runtime-contract "${BACKEND_RUNTIME_CONTRACT_OUT}" \
  --workload-json "${workload_json}" \
  --instrumentation "lightweight_backend_trace" \
  --instrumentation "cuda_event_load_status" \
  --instrumentation "streamed_decode_timing" \
  --artifact "command=${COMMAND_PATH}" \
  --artifact "control_probe=${RUN_ROOT}/decode_control/probe_run.json" \
  --artifact "single_probe=${RUN_ROOT}/single_reload/probe_run.json" \
  --artifact "sustained_probe=${RUN_ROOT}/sustained_reload/probe_run.json" \
  --artifact "summary=${RUN_ROOT}/sustained_kv_pressure_summary.json" \
  --artifact "report=${RUN_ROOT}/sustained_kv_pressure_report.html" \
  --completion-status complete

echo "Complete: ${RUN_ROOT}/sustained_kv_pressure_report.html"
